# docker compose -f docker-compose.local.yml up -d --build (After editing)
# docker compose -f docker-compose.local.yml logs -f
# docker compose -f docker-compose.local.yml down

# Local development docker-compose configuration

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: UTC
    volumes:
      - pgdata_local:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./backend/.env.prod
    environment:
      NPM_CONFIG_CACHE: /tmp/.npm
      TZ: UTC
    command: sh -c "npm start"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./nginx/key.pem:/etc/ssl/private/key.pem:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata_local:
